# Generated by Django 5.2 on 2025-05-21 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0002_reviews'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ManyToManyField(blank=True, related_name='in_cart', to='library.book')),
                ('favorite_authors', models.ManyToManyField(blank=True, related_name='favorited_by', to='library.author')),
                ('favorite_books', models.ManyToManyField(blank=True, related_name='favorited_by', to='library.book')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
